---
name: release
on:
  push:
    branches:
      - main
jobs:
  tagpr:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          token: ${{ secrets.TAGPR_GITHUB_PAT }}
      - uses: aquaproj/aqua-installer@5e54e5cee8a95ee2ce7c04cb993da6dfad13e59c # v3.1.2
        with:
          aqua_version: v2.43.3
      - run: aqua install
      - name: run tagpr
        run: tagpr
        env:
          GITHUB_TOKEN: ${{ secrets.TAGPR_GITHUB_PAT }}
